version: '2'
services:
  postgres:
    restart: always
    image: postgres
    env_file: .env
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: ./compose/django/gunicorn.sh
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - postgres
  nginx:
    restart: always
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:8080:80"
    volumes:
        - ./static:/var/www